name: Crookie
favicon: null
layout_spectrum: 0.7516
typography_spectrum: 0.41014
title: Welcome to Crookie.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-44610790-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4e5659'
    - '#01111e'
    - '#02455f'
    - '#9e9fa3'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.4145503626205027
purpose: []
