layout_spectrum: 0.039473757147789
typography_spectrum: 0.7137176448013633
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.28508650860749185
  lightness: 0.18796752975322306
  saturation: 0.9569169292226434
  rhythmicContrast: 0.12422085204161704
name: Crookie
favicon: null
title: Welcome to Crookie.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-44610790-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
